---
- name: ACI Demo Create VRF in a tenant
  hosts: aci
  connection: local
  gather_facts: no

  tasks:
    - name: Create a new VRF in an ACI tenant "{{ the_tenant }}"
      cisco.aci.aci_vrf:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        vrf: "{{ the_vrf }}"
        tenant: "{{ the_tenant }}"
        descr: VRF Created by Ansible 
        policy_control_preference: enforced
        policy_control_direction: ingress
        state: present
      delegate_to: localhost
