---
- name: ACI Demo create BD bridge domains
  hosts: aci
  connection: local
  gather_facts: no

  tasks:
    - name: Create Bridge Domains
      cisco.aci.aci_bd:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{ the_tenant }}"
        bd: "{{ item }}"
        mac_address: "{{ the_mac }}"
        vrf: "{{ the_vrf }}"
        state: present
      loop: "{{ the_bds }}"
      delegate_to: localhost
