---
- name: ACI Demo Create Tenant
  hosts: aci
  connection: local
  gather_facts: no

  tasks:
    - name: Create an ACI Tenant "{{ the_tenant }}"
      cisco.aci.aci_tenant:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{ the_tenant }}"
        description: "Tenant created by Red Hat Ansible Automation Platform"
        state: present
