---
- name: ACI Demo create an API and an EPG
  hosts: aci
  connection: local
  gather_facts: no

  tasks:
    - name: Create an ACI Application profile
      cisco.aci.aci_ap:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{ the_tenant }}"
        ap: "{{ the_ap }}"
        description: AP created by Ansible
        state: present
      delegate_to: localhost

    - name: Create an ACI EPG 
      cisco.aci.aci_epg:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{ the_tenant }}"
        ap: "{{ the_ap }}"
        epg: "{{ the_epg }}"
        description: EPG Created by Ansible
        bd: "{{ the_bds.0 }}"
        priority: unspecified
        intra_epg_isolation: unenforced
        state: present
      delegate_to: localhost
