- name: Get ACI tenant
  hosts: aci
  connection: local
  gather_facts: no

  tasks:
    - name: get ACI gather Tenants
      cisco.aci.aci_tenant:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: 00_RH_ANSIBLE_TENANT_DEMO
        description: RH_Ansible_Demo
        state: query
      register: output

    - name: show tenant
      debug:
        msg: "Tenant's name is {{ output.current[0].fvTenant.attributes.name }}"
