---
- name: ACI Demo create BD bridge domain
  hosts: aci
  connection: local
  gather_facts: no

  tasks:
    - name: Get Bridge Domain1
      cisco.aci.aci_bd:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{ the_tenant }}"
        state: query
      register: output
      delegate_to: localhost

    - name: Show Bridge Domain
      debug:
        msg: "Bridge Domain name is {{ output }}"


#
#    - name: show Bridge Domain
#      debug:
#        msg: "Bridge Domain name is {{ output.current[0].fvBD.attributes.name }}"
