- name: Get ACI epgs
  hosts: aci
  connection: local
  gather_facts: no

  tasks:
    - name: ACI gather epgs
      aci_epg:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        state: query
