---
- name: ACI Demo Remove Tenant
  hosts: aci
  connection: local
  gather_facts: no


  tasks:
    - name: Remove ACI Tenant <ANSIBLE_TENANT>
      cisco.aci.aci_tenant:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{ the_tenant }}" 
        state: absent
