---
- name: ACI Demo remove epg
  hosts: aci
  connection: local
  gather_facts: no

  tasks:
    - name: Remove ACI EPG RH_EPG_DEMO
      cisco.aci.aci_epg:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: 00_NORVILLE_ANSIBLE_DEMO
        ap: "{{ the_ap }}"
        epg: "{{ the_epg }}"
        description: rh_norville_epg_demo
        bd: "{{ the_bds }}"
        priority: unspecified
        intra_epg_isolation: unenforced
        state: absent
      delegate_to: localhost
