---
- name: ACI Demo remove VRF
  hosts: aci
  connection: local
  gather_facts: no
  vars:
    the_tenant: 00_NORVILLE_ANSIBLE_DEMO
    the_vrf: norville_vrf_demo

  tasks:
    - name: Remove a VRF from a tenant
      cisco.aci.aci_vrf:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        vrf: "{{ the_vrf }}"
        tenant: "{{ the_tenant }}"
        policy_control_preference: enforced
        policy_control_direction: ingress
        state: absent
      delegate_to: localhost
