---
- name: ACI Demo Remove Tenant
  hosts: aci
  connection: local
  gather_facts: no

  tasks:
    - name: Remove ACI Tenant <ANSIBLE_TENANT>
      aci_tenant:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: 00_RH_ANSIBLE_TENANT_DEMO
        description: Create by RH_Ansible!
        state: absent
